### ISSUE TITLE
Incorrect trainning data?

### ISSUE THREAD

**Issue by lychees** [openai/prm800k#9]
```
[{"question": "The first four terms in an arithmetic sequence are $x+y$, $x-y$, $xy$, and $x/y$, in that order. What is the fifth term? Express your answer as a common fraction."}] 
```

I really didn't understand why this answer is 123/40, is the data missing some conditions?

**Comment by alreadydone** [comment]
The common difference is `(x-y)-(x+y)=-2y`. Since the four terms form an arithmetic sequence we must have `xy-(x-y)=-2y` and `x/y-xy=-2y` as well. From  `xy-(x-y)=-2y` we can solve `y=x/(x+3)`. Plugging this into `x/y-xy=-2y` we get an equation in `x`, from which we solve `x=-9/8` and `y=-3/5`. The fifth  term is then `x/y-2y=123/40`.

I asked the question to ChatGPT(-3.5) and Bard and their procedures all make sense, but none arrived at the correct answer; I didn't attempt to pick out the erroneous step(s). Claude 2 always give an answer with x and y in it, and when asked to give a numeric answer, it only knows to try some random values of x and y ...

**Comment by alreadydone** [comment]
After some prompting (pointing out errors), I was able to get Bing (GPT-4) solve it: [Conversation.pdf](https://github.com/openai/prm800k/files/12062476/Conversation.pdf). Being able to see rendered LaTeX in Bing makes it much smoother to offer feedback, but regrettably ChatGPT, poe.com, and Claude doesn't render LaTeX in its interface. Bard interface renders inline LaTeX but doesn't render `\begin{align*} \end{align*}`. The study conducted in [*Evaluating Language Models for Mathematics through Interactions*](https://twitter.com/wtgowers/status/1665704305733558272) also had LaTeX rendered.

At one point I mistakenly copied the rendered LaTeX (which becomes malformed text `y−1−3 =y−1−3y −2y`) rather than original text; this is corrected in my next input.

**Comment by Huntrr** [comment]
I think there are some MATH dataset questions with incorrect final answers. I don't think it matters too much (our labelers probably made small mistakes more often than the MATH answer key was wrong).

This one definitely looks right though!
